# Generated by Django 3.2 on 2022-02-21 12:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='jon@gmail.com', max_length=254)),
                ('event_type', models.CharField(blank=True, choices=[('WEDDING', 'Wedding'), ('CHRISTENING', 'Christening'), ('OTHER', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('info', models.TextField(max_length=500)),
                ('event_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Confirmed')], default=0)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
