# Generated by Django 3.2 on 2022-02-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220224_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit',
            options={'ordering': ['event_date']},
        ),
    ]
