# Generated by Django 3.2 on 2022-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_booking_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='username',
        ),
    ]
