# Generated by Django 3.2 on 2022-02-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_user_booking_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user',
        ),
    ]
