# Generated by Django 3.2 on 2022-02-28 21:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_username_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
