# Generated by Django 3.2 on 2022-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_booking_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, choices=[('WEDDING', 'Wedding'), ('CHRISTENING', 'Christening'), ('FAMILY SHOOTS', 'Family Shoots'), ('COUPLE SHOOTS', 'Couple Shoots'), ('PERSONAL SHOOTS', 'Personal Shoots'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='event_type',
            field=models.CharField(blank=True, choices=[('WEDDING', 'Wedding'), ('CHRISTENING', 'Christening'), ('FAMILY SHOOTS', 'Family Shoots'), ('COUPLE SHOOTS', 'Couple Shoots'), ('PERSONAL SHOOTS', 'Personal Shoots'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('WEDDING', 'Wedding'), ('CHRISTENING', 'Christening'), ('FAMILY SHOOTS', 'Family Shoots'), ('COUPLE SHOOTS', 'Couple Shoots'), ('PERSONAL SHOOTS', 'Personal Shoots'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
